from setuptools import setup

setup(
    name='EventosUniandes',
    version='1.0',
    packages=['Lib.site-packages.PIL', 'Lib.site-packages.pip', 'Lib.site-packages.pip._vendor',
              'Lib.site-packages.pip._vendor.idna', 'Lib.site-packages.pip._vendor.pep517',
              'Lib.site-packages.pip._vendor.pytoml', 'Lib.site-packages.pip._vendor.certifi',
              'Lib.site-packages.pip._vendor.chardet', 'Lib.site-packages.pip._vendor.chardet.cli',
              'Lib.site-packages.pip._vendor.distlib', 'Lib.site-packages.pip._vendor.distlib._backport',
              'Lib.site-packages.pip._vendor.msgpack', 'Lib.site-packages.pip._vendor.urllib3',
              'Lib.site-packages.pip._vendor.urllib3.util', 'Lib.site-packages.pip._vendor.urllib3.contrib',
              'Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'Lib.site-packages.pip._vendor.urllib3.packages',
              'Lib.site-packages.pip._vendor.urllib3.packages.rfc3986',
              'Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'Lib.site-packages.pip._vendor.colorama', 'Lib.site-packages.pip._vendor.html5lib',
              'Lib.site-packages.pip._vendor.html5lib._trie', 'Lib.site-packages.pip._vendor.html5lib.filters',
              'Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'Lib.site-packages.pip._vendor.html5lib.treebuilders', 'Lib.site-packages.pip._vendor.lockfile',
              'Lib.site-packages.pip._vendor.progress', 'Lib.site-packages.pip._vendor.requests',
              'Lib.site-packages.pip._vendor.packaging', 'Lib.site-packages.pip._vendor.cachecontrol',
              'Lib.site-packages.pip._vendor.cachecontrol.caches', 'Lib.site-packages.pip._vendor.webencodings',
              'Lib.site-packages.pip._vendor.pkg_resources', 'Lib.site-packages.pip._internal',
              'Lib.site-packages.pip._internal.cli', 'Lib.site-packages.pip._internal.req',
              'Lib.site-packages.pip._internal.vcs', 'Lib.site-packages.pip._internal.utils',
              'Lib.site-packages.pip._internal.models', 'Lib.site-packages.pip._internal.commands',
              'Lib.site-packages.pip._internal.operations', 'Lib.site-packages.pip._internal.distributions',
              'Lib.site-packages.idna', 'Lib.site-packages.pytz', 'Lib.site-packages.boto3',
              'Lib.site-packages.boto3.s3', 'Lib.site-packages.boto3.ec2', 'Lib.site-packages.boto3.docs',
              'Lib.site-packages.boto3.dynamodb', 'Lib.site-packages.boto3.resources', 'Lib.site-packages.isort',
              'Lib.site-packages.wrapt', 'Lib.site-packages.django', 'Lib.site-packages.django.db',
              'Lib.site-packages.django.db.models', 'Lib.site-packages.django.db.models.sql',
              'Lib.site-packages.django.db.models.fields', 'Lib.site-packages.django.db.models.functions',
              'Lib.site-packages.django.db.backends', 'Lib.site-packages.django.db.backends.base',
              'Lib.site-packages.django.db.backends.dummy', 'Lib.site-packages.django.db.backends.mysql',
              'Lib.site-packages.django.db.backends.oracle', 'Lib.site-packages.django.db.backends.sqlite3',
              'Lib.site-packages.django.db.backends.postgresql',
              'Lib.site-packages.django.db.backends.postgresql_psycopg2', 'Lib.site-packages.django.db.migrations',
              'Lib.site-packages.django.db.migrations.operations', 'Lib.site-packages.django.apps',
              'Lib.site-packages.django.conf', 'Lib.site-packages.django.conf.urls',
              'Lib.site-packages.django.conf.locale', 'Lib.site-packages.django.conf.locale.ar',
              'Lib.site-packages.django.conf.locale.az', 'Lib.site-packages.django.conf.locale.bg',
              'Lib.site-packages.django.conf.locale.bn', 'Lib.site-packages.django.conf.locale.bs',
              'Lib.site-packages.django.conf.locale.ca', 'Lib.site-packages.django.conf.locale.cs',
              'Lib.site-packages.django.conf.locale.cy', 'Lib.site-packages.django.conf.locale.da',
              'Lib.site-packages.django.conf.locale.de', 'Lib.site-packages.django.conf.locale.el',
              'Lib.site-packages.django.conf.locale.en', 'Lib.site-packages.django.conf.locale.eo',
              'Lib.site-packages.django.conf.locale.es', 'Lib.site-packages.django.conf.locale.et',
              'Lib.site-packages.django.conf.locale.eu', 'Lib.site-packages.django.conf.locale.fa',
              'Lib.site-packages.django.conf.locale.fi', 'Lib.site-packages.django.conf.locale.fr',
              'Lib.site-packages.django.conf.locale.fy', 'Lib.site-packages.django.conf.locale.ga',
              'Lib.site-packages.django.conf.locale.gd', 'Lib.site-packages.django.conf.locale.gl',
              'Lib.site-packages.django.conf.locale.he', 'Lib.site-packages.django.conf.locale.hi',
              'Lib.site-packages.django.conf.locale.hr', 'Lib.site-packages.django.conf.locale.hu',
              'Lib.site-packages.django.conf.locale.id', 'Lib.site-packages.django.conf.locale.is',
              'Lib.site-packages.django.conf.locale.it', 'Lib.site-packages.django.conf.locale.ja',
              'Lib.site-packages.django.conf.locale.ka', 'Lib.site-packages.django.conf.locale.km',
              'Lib.site-packages.django.conf.locale.kn', 'Lib.site-packages.django.conf.locale.ko',
              'Lib.site-packages.django.conf.locale.lt', 'Lib.site-packages.django.conf.locale.lv',
              'Lib.site-packages.django.conf.locale.mk', 'Lib.site-packages.django.conf.locale.ml',
              'Lib.site-packages.django.conf.locale.mn', 'Lib.site-packages.django.conf.locale.nb',
              'Lib.site-packages.django.conf.locale.nl', 'Lib.site-packages.django.conf.locale.nn',
              'Lib.site-packages.django.conf.locale.pl', 'Lib.site-packages.django.conf.locale.pt',
              'Lib.site-packages.django.conf.locale.ro', 'Lib.site-packages.django.conf.locale.ru',
              'Lib.site-packages.django.conf.locale.sk', 'Lib.site-packages.django.conf.locale.sl',
              'Lib.site-packages.django.conf.locale.sq', 'Lib.site-packages.django.conf.locale.sr',
              'Lib.site-packages.django.conf.locale.sv', 'Lib.site-packages.django.conf.locale.ta',
              'Lib.site-packages.django.conf.locale.te', 'Lib.site-packages.django.conf.locale.th',
              'Lib.site-packages.django.conf.locale.tr', 'Lib.site-packages.django.conf.locale.uk',
              'Lib.site-packages.django.conf.locale.vi', 'Lib.site-packages.django.conf.locale.de_CH',
              'Lib.site-packages.django.conf.locale.en_AU', 'Lib.site-packages.django.conf.locale.en_GB',
              'Lib.site-packages.django.conf.locale.es_AR', 'Lib.site-packages.django.conf.locale.es_CO',
              'Lib.site-packages.django.conf.locale.es_MX', 'Lib.site-packages.django.conf.locale.es_NI',
              'Lib.site-packages.django.conf.locale.es_PR', 'Lib.site-packages.django.conf.locale.pt_BR',
              'Lib.site-packages.django.conf.locale.sr_Latn', 'Lib.site-packages.django.conf.locale.zh_Hans',
              'Lib.site-packages.django.conf.locale.zh_Hant', 'Lib.site-packages.django.core',
              'Lib.site-packages.django.core.mail', 'Lib.site-packages.django.core.mail.backends',
              'Lib.site-packages.django.core.cache', 'Lib.site-packages.django.core.cache.backends',
              'Lib.site-packages.django.core.files', 'Lib.site-packages.django.core.checks',
              'Lib.site-packages.django.core.checks.security', 'Lib.site-packages.django.core.checks.compatibility',
              'Lib.site-packages.django.core.servers', 'Lib.site-packages.django.core.handlers',
              'Lib.site-packages.django.core.management', 'Lib.site-packages.django.core.serializers',
              'Lib.site-packages.django.http', 'Lib.site-packages.django.test', 'Lib.site-packages.django.urls',
              'Lib.site-packages.django.forms', 'Lib.site-packages.django.utils',
              'Lib.site-packages.django.utils.translation', 'Lib.site-packages.django.views',
              'Lib.site-packages.django.views.generic', 'Lib.site-packages.django.views.decorators',
              'Lib.site-packages.django.contrib', 'Lib.site-packages.django.contrib.gis',
              'Lib.site-packages.django.contrib.gis.db', 'Lib.site-packages.django.contrib.gis.db.models',
              'Lib.site-packages.django.contrib.gis.db.models.sql', 'Lib.site-packages.django.contrib.gis.db.backends',
              'Lib.site-packages.django.contrib.gis.db.backends.base',
              'Lib.site-packages.django.contrib.gis.db.backends.mysql',
              'Lib.site-packages.django.contrib.gis.db.backends.oracle',
              'Lib.site-packages.django.contrib.gis.db.backends.postgis',
              'Lib.site-packages.django.contrib.gis.db.backends.spatialite',
              'Lib.site-packages.django.contrib.gis.gdal', 'Lib.site-packages.django.contrib.gis.gdal.raster',
              'Lib.site-packages.django.contrib.gis.gdal.prototypes', 'Lib.site-packages.django.contrib.gis.geos',
              'Lib.site-packages.django.contrib.gis.geos.prototypes', 'Lib.site-packages.django.contrib.gis.admin',
              'Lib.site-packages.django.contrib.gis.forms', 'Lib.site-packages.django.contrib.gis.utils',
              'Lib.site-packages.django.contrib.gis.geoip2', 'Lib.site-packages.django.contrib.gis.sitemaps',
              'Lib.site-packages.django.contrib.gis.serializers', 'Lib.site-packages.django.contrib.auth',
              'Lib.site-packages.django.contrib.auth.handlers', 'Lib.site-packages.django.contrib.auth.management',
              'Lib.site-packages.django.contrib.auth.migrations', 'Lib.site-packages.django.contrib.admin',
              'Lib.site-packages.django.contrib.admin.views', 'Lib.site-packages.django.contrib.admin.migrations',
              'Lib.site-packages.django.contrib.admin.templatetags', 'Lib.site-packages.django.contrib.sites',
              'Lib.site-packages.django.contrib.sites.migrations', 'Lib.site-packages.django.contrib.humanize',
              'Lib.site-packages.django.contrib.humanize.templatetags', 'Lib.site-packages.django.contrib.messages',
              'Lib.site-packages.django.contrib.messages.storage', 'Lib.site-packages.django.contrib.postgres',
              'Lib.site-packages.django.contrib.postgres.forms', 'Lib.site-packages.django.contrib.postgres.fields',
              'Lib.site-packages.django.contrib.postgres.aggregates', 'Lib.site-packages.django.contrib.sessions',
              'Lib.site-packages.django.contrib.sessions.backends',
              'Lib.site-packages.django.contrib.sessions.migrations', 'Lib.site-packages.django.contrib.sitemaps',
              'Lib.site-packages.django.contrib.admindocs', 'Lib.site-packages.django.contrib.flatpages',
              'Lib.site-packages.django.contrib.flatpages.migrations',
              'Lib.site-packages.django.contrib.flatpages.templatetags', 'Lib.site-packages.django.contrib.redirects',
              'Lib.site-packages.django.contrib.redirects.migrations', 'Lib.site-packages.django.contrib.staticfiles',
              'Lib.site-packages.django.contrib.staticfiles.templatetags',
              'Lib.site-packages.django.contrib.syndication', 'Lib.site-packages.django.contrib.contenttypes',
              'Lib.site-packages.django.contrib.contenttypes.management',
              'Lib.site-packages.django.contrib.contenttypes.migrations', 'Lib.site-packages.django.dispatch',
              'Lib.site-packages.django.template', 'Lib.site-packages.django.template.loaders',
              'Lib.site-packages.django.template.backends', 'Lib.site-packages.django.middleware',
              'Lib.site-packages.django.templatetags', 'Lib.site-packages.pylint', 'Lib.site-packages.pylint.test.data',
              'Lib.site-packages.pylint.test.input', 'Lib.site-packages.pylint.test.input.func_w0401_package',
              'Lib.site-packages.pylint.test.extensions', 'Lib.site-packages.pylint.test.functional',
              'Lib.site-packages.pylint.test.regrtest_data.dummy', 'Lib.site-packages.pylint.test.regrtest_data.absimp',
              'Lib.site-packages.pylint.test.regrtest_data.package',
              'Lib.site-packages.pylint.test.regrtest_data.package.subpackage',
              'Lib.site-packages.pylint.test.regrtest_data.beyond_top',
              'Lib.site-packages.pylint.test.regrtest_data.bad_package',
              'Lib.site-packages.pylint.test.regrtest_data.package_all',
              'Lib.site-packages.pylint.test.regrtest_data.init_wildcard', 'Lib.site-packages.pylint.checkers',
              'Lib.site-packages.pylint.pyreverse', 'Lib.site-packages.pylint.reporters',
              'Lib.site-packages.pylint.reporters.ureports', 'Lib.site-packages.pylint.extensions',
              'Lib.site-packages.astroid', 'Lib.site-packages.astroid.interpreter',
              'Lib.site-packages.astroid.interpreter._import', 'Lib.site-packages.certifi', 'Lib.site-packages.chardet',
              'Lib.site-packages.chardet.cli', 'Lib.site-packages.urllib3', 'Lib.site-packages.urllib3.util',
              'Lib.site-packages.urllib3.contrib', 'Lib.site-packages.urllib3.contrib._securetransport',
              'Lib.site-packages.urllib3.packages', 'Lib.site-packages.urllib3.packages.backports',
              'Lib.site-packages.urllib3.packages.ssl_match_hostname', 'Lib.site-packages.botocore',
              'Lib.site-packages.botocore.docs', 'Lib.site-packages.botocore.docs.bcdoc',
              'Lib.site-packages.botocore.vendored', 'Lib.site-packages.botocore.vendored.requests',
              'Lib.site-packages.botocore.vendored.requests.packages',
              'Lib.site-packages.botocore.vendored.requests.packages.chardet',
              'Lib.site-packages.botocore.vendored.requests.packages.urllib3',
              'Lib.site-packages.botocore.vendored.requests.packages.urllib3.util',
              'Lib.site-packages.botocore.vendored.requests.packages.urllib3.contrib',
              'Lib.site-packages.botocore.vendored.requests.packages.urllib3.packages',
              'Lib.site-packages.botocore.vendored.requests.packages.urllib3.packages.ssl_match_hostname',
              'Lib.site-packages.colorama', 'Lib.site-packages.dateutil', 'Lib.site-packages.dateutil.tz',
              'Lib.site-packages.dateutil.parser', 'Lib.site-packages.dateutil.zoneinfo', 'Lib.site-packages.docutils',
              'Lib.site-packages.docutils.utils', 'Lib.site-packages.docutils.utils.math',
              'Lib.site-packages.docutils.parsers', 'Lib.site-packages.docutils.parsers.rst',
              'Lib.site-packages.docutils.parsers.rst.languages', 'Lib.site-packages.docutils.parsers.rst.directives',
              'Lib.site-packages.docutils.readers', 'Lib.site-packages.docutils.writers',
              'Lib.site-packages.docutils.writers.xetex', 'Lib.site-packages.docutils.writers.latex2e',
              'Lib.site-packages.docutils.writers.odf_odt', 'Lib.site-packages.docutils.writers.s5_html',
              'Lib.site-packages.docutils.writers.pep_html', 'Lib.site-packages.docutils.writers.html4css1',
              'Lib.site-packages.docutils.writers.html5_polyglot', 'Lib.site-packages.docutils.languages',
              'Lib.site-packages.docutils.transforms', 'Lib.site-packages.gunicorn', 'Lib.site-packages.gunicorn.app',
              'Lib.site-packages.gunicorn.http', 'Lib.site-packages.gunicorn.workers',
              'Lib.site-packages.gunicorn.instrument', 'Lib.site-packages.jmespath', 'Lib.site-packages.psycopg2',
              'Lib.site-packages.psycopg2.tests', 'Lib.site-packages.requests', 'Lib.site-packages.sqlparse',
              'Lib.site-packages.sqlparse.engine', 'Lib.site-packages.sqlparse.filters', 'Lib.site-packages.storages',
              'Lib.site-packages.storages.backends', 'Lib.site-packages.s3transfer', 'Lib.site-packages.whitenoise',
              'Lib.site-packages.whitenoise.runserver_nostatic',
              'Lib.site-packages.whitenoise.runserver_nostatic.management',
              'Lib.site-packages.whitenoise.runserver_nostatic.management.commands', 'Lib.site-packages.corsheaders',
              'Lib.site-packages.django_heroku', 'Lib.site-packages.rest_framework',
              'Lib.site-packages.rest_framework.utils', 'Lib.site-packages.rest_framework.schemas',
              'Lib.site-packages.rest_framework.authtoken', 'Lib.site-packages.rest_framework.authtoken.management',
              'Lib.site-packages.rest_framework.authtoken.management.commands',
              'Lib.site-packages.rest_framework.authtoken.migrations', 'Lib.site-packages.rest_framework.management',
              'Lib.site-packages.rest_framework.management.commands', 'Lib.site-packages.rest_framework.templatetags',
              'Lib.site-packages.mypy_drf_plugin', 'Lib.site-packages.mypy_drf_plugin.lib',
              'Lib.site-packages.mypy_drf_plugin.transformers', 'Lib.site-packages.lazy_object_proxy',
              'Lib.site-packages.virtualenv_support', 'Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations', 'EventosUniandes',
              'eventos_uniandes_app.migrations'],
    url='',
    license='',
    author='Fabian Laverde',
    author_email='jf.laverde@uniandes.edu.co',
    description=''
)
